FROM php:8.1-fpm-alpine
WORKDIR /var/www
RUN apk update
RUN apk update && apk add zlib-dev libzip-dev unzip

## Install PHP extensions
RUN docker-php-ext-install bcmath
RUN docker-php-ext-install zip
RUN docker-php-ext-install opcache
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN apk --no-cache add \
    mysql-client \
    libzip-dev \
    && docker-php-ext-install pdo_mysql zip